"""fix quote column

Revision ID: a3f8decaa4fa
Revises: d1c89c690c5f
Create Date: 2026-07-15 22:39:02.724053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f8decaa4fa'
down_revision: Union[str, Sequence[str], None] = 'd1c89c690c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'quote')
    op.add_column('words', sa.Column('quote', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'quote')
    op.add_column('sources', sa.Column('quote', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
